groups:
  - name: prompt_sentinel_performance
    interval: 30s
    rules:
      # Cache Performance
      - alert: LowCacheHitRate
        expr: |
          rate(prompt_sentinel_cache_hits_total[10m]) /
          (rate(prompt_sentinel_cache_hits_total[10m]) + rate(prompt_sentinel_cache_misses_total[10m])) < 0.7
        for: 15m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "Cache hit rate below 70%"
          description: "Cache {{ $labels.cache_type }} hit rate is {{ $value | humanizePercentage }}"
          action: "Review cache configuration and TTL settings"

      - alert: HighCacheEvictionRate
        expr: rate(prompt_sentinel_cache_evictions_total[5m]) > 10
        for: 10m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High cache eviction rate"
          description: "Cache evicting {{ $value }} items per second"

      # Resource Usage
      - alert: HighMemoryUsage
        expr: |
          prompt_sentinel_cache_size_bytes / (1024 * 1024 * 1024) > 4
        for: 10m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High memory usage (>4GB)"
          description: "Cache memory usage is {{ $value }}GB"

      - alert: HighActiveRequests
        expr: prompt_sentinel_active_requests > 100
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High number of active requests"
          description: "{{ $value }} requests currently being processed"

      # Queue Monitoring
      - alert: QueueBacklog
        expr: prompt_sentinel_queue_size > 50
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "Large queue backlog"
          description: "Queue {{ $labels.queue_name }} has {{ $value }} items"

      # Rate Limiting
      - alert: HighRateLimitHits
        expr: rate(prompt_sentinel_rate_limit_hits_total[5m]) > 1
        for: 10m
        labels:
          severity: info
          team: platform
        annotations:
          summary: "Clients hitting rate limits"
          description: "Client {{ $labels.client_id }} hitting rate limits ({{ $value }}/s)"

      # Detection Performance
      - alert: SlowDetection
        expr: |
          histogram_quantile(0.95, rate(prompt_sentinel_detection_duration_seconds_bucket[5m])) > 0.2
        for: 10m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "Slow detection processing"
          description: "Detection P95 latency is {{ $value }}s (threshold: 200ms)"

      # Pattern Matching Performance
      - alert: HighPatternMatchRate
        expr: rate(prompt_sentinel_pattern_matches_total[5m]) > 100
        for: 5m
        labels:
          severity: info
          team: ml
        annotations:
          summary: "High pattern match rate"
          description: "Pattern matching at {{ $value }} matches/second"
